
"""CIFAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ayJGJqAbZpie9K5fRsLm6bb8s748Ch1

**CIFAR-10 Image Classification using ML and DL**

Lab By:
Aabhiskar KC(1)
Abhishek Yadav(4)
Krishna Subedi(17)
Manoj Rai(21)
"""

import tensorflow as tf
import numpy as np
import os
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
#from google.colab import drive
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import joblib

#drive.mount('/content/drive')
drive_dir='./keras_cifar10'
os.makedirs(drive_dir,exist_ok=True)
file_path=os.path.join(drive_dir,'cifar10.npz')

if os.path.exists(file_path):
  with np.load(file_path) as data:
    train_images,train_labels=data['train_images'],data['train_labels']
    test_images,test_labels=data['test_images'],data['test_labels']
    print("Loaded CIFAR-10 from Google Drive")
else:
  (train_images,train_labels), (test_images,test_labels)=datasets.cifar10.load_data()
  np.savez(file_path, train_images=train_images,train_labels=train_labels,test_images=test_images,test_labels=test_labels)
  print("Downloaded and saved CIFAR-10 to Google Drive")

#Visualizing the class distribution for training data
class_names=[
    'airplane',
    'automobile',
    'bird',
    'cat',
    'deer',
    'dog',
    'frog',
    'horse',
    'ship',
    'truck'
]

class_id,test_count_train=np.unique(train_labels,return_counts=True)
class_id,count_test=np.unique(test_labels,return_counts=True)

fig,(graph1,graph2)= plt.subplots(1,2,figsize=(10,3))
graph1.barh(class_names,test_count_train,color='orange')
graph1.set_ylabel('Classes')
graph2.barh(class_names,count_test)
graph2.set_title('Test Data')
plt.show()

print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

#Pre-proccessing the images' pixel value to be normalized from 0 to 1

train_images,test_images = train_images/255.0, test_images/255.0

#Displaying few images from the training data
plt.figure(figsize=(12,12))

for i in range(25):
  index=np.random.randint(0,50000)
  plt.subplot(5,5,i+1)
  plt.imshow(train_images[index])
  plt.title(class_names[train_labels[index][0]])
  plt.axis("off")

plt.show()

#Building the model
model_cnn=models.Sequential()

model_cnn.add(layers.Input(shape=(32,32,3)))

model_cnn.add(layers.Conv2D(32,
                        (3,3),
                        activation='relu'))

model_cnn.add(layers.MaxPooling2D(2,2))

model_cnn.add(layers.Conv2D(64,
                        (3,3),
                        activation='relu'))

model_cnn.add(layers.MaxPooling2D(2,2))

model_cnn.add(layers.Conv2D(64,
                        (3,3),
                        activation='relu'))
model_cnn.add(layers.Flatten())
model_cnn.add(layers.Dense(64,activation='relu'))
model_cnn.add(layers.Dense(10))

model_cnn.summary()

loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

model_cnn.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

file_path='./keras_cifar10/cifar10_model_cnn.keras'
print(os.listdir('./keras_cifar10'))
if os.path.exists(file_path):
  model_cnn=tf.keras.models.load_model(file_path)
  history=np.load('./keras_cifar10/history/history.npy',allow_pickle=True).item()
else:
    history=model_cnn.fit(train_images,train_labels,epochs=10)
    os.makedirs('./keras_cifar10/history',exist_ok=True)
    np.save('./keras_cifar10/history/history.npy', history.history)
    model_cnn.save(file_path)

#plt.plot(history['accuracy'],label='accuracy')
# plt.plot(history['val_accuracy'],label='val_accuracy')
#plt.xlabel('Epoch')
#plt.ylabel('Accuracy')
#plt.xticks(range(1,20,2))
#plt.legend(loc='lower right')
#plt.show()
#print("Best Validation Accuracy of: ",np.max(history['val_accuracy'])," in Epoch:", np.argmax(history['val_accuracy']))

test_loss,test_acc=model_cnn.evaluate(test_images,test_labels)
print(f"The accuracy for test images is:{test_acc*100:.2f}%")

prediction_model=models.Sequential([model_cnn,layers.Softmax()])
predictions_cnn=prediction_model.predict(test_images)
history['accuracy']

def plot_image(i, predictions, true_label, img):
    true_label, img = true_label[i][0], img[i]

    predicted_label = np.argmax(predictions)
    confidence = float(np.max(predictions))

    plt.grid(False)
    plt.imshow(img)

    if predicted_label == true_label:
        color = 'blue'
    else:
        color = 'red'

    plt.xlabel(
        f"{class_names[predicted_label]} "
        f"{confidence * 100:.2f}% "
        f"({class_names[true_label]})",
        color=color
    )
def plot_graph(i, predictions_array, true_label):
  true_label = true_label[i][0]
  plt.grid(False)
  thisplot = plt.barh(class_names, predictions_array, color="#777777")
  plt.xlim([0, 1])
  predicted_label = np.argmax(predictions_array)
  thisplot[predicted_label].set_color('red')
  thisplot[true_label].set_color('blue')

def display_predictions(num_rows, num_cols, predictions, title):
    num_images = num_rows * num_cols

    plt.figure(figsize=(2*2*num_cols, 2*num_rows))

    for i in range(num_images):
        plt.subplot(num_rows, 2*num_cols, 2*i+1)

        index = np.random.randint(0, 10000)

        plot_image(
            index,
            predictions[index],
            test_labels,
            test_images
        )

        plt.subplot(num_rows, 2*num_cols, 2*i+2)

        plot_graph(
            index,
            predictions[index],
            test_labels
        )

    plt.suptitle(title, fontsize=16)
    plt.tight_layout()

    plt.show()

accuracy_cnn=accuracy_score(
    test_labels,
    np.argmax(predictions_cnn,axis=1)
)
#displaying predictions of CNN
display_predictions(
    5,
    3,
    predictions_cnn,
    "Convolutional Neural Network"
)

"""# Machine Learning Algorithms

**Random Forest Classifier**
"""

#Preprocessing
train_features=train_images.reshape(
   train_images.shape[0],-1
)
test_features=test_images.reshape(
    test_images.shape[0],-1
)

print(f"Reshaped train images: {train_features.shape}")
print(f"Reshaped test images: {test_features.shape}")

# =========================
# RANDOM FOREST
# =========================
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

file_path = './keras_cifar10/rf_model.joblib'

if os.path.exists(file_path):
    print("Loading saved Random Forest model...")
    rf = joblib.load(file_path)
else:
    print("Training Random Forest...")
    rf.fit(
        train_features,
        train_labels.ravel()
    )
    joblib.dump(rf, file_path)

rf_predictions = rf.predict(test_features)

rf_probabilities = rf.predict_proba(test_features)

display_predictions(
    5, 3,
    rf_probabilities,
    "Random Forest"
)

accuracy_rf = accuracy_score(
    test_labels.ravel(),
    rf_predictions
)

print(f"Accuracy for Random Forest: {accuracy_rf * 100:.2f}%")
# =========================
# KNN
# =========================

knn = KNeighborsClassifier(
        n_neighbors=5, 
        n_jobs=-1, 
        algorithm='kd_tree'
)

file_path = './keras_cifar10/knn_model.joblib'

if os.path.exists(file_path):
    print("Loading saved KNN model...")
    knn = joblib.load(file_path)
else:
    print("Training KNN...")
    knn.fit(
        train_features,
        train_labels.ravel()
    )
    joblib.dump(knn, file_path)

knn_predictions = knn.predict(test_features)
knn_probabilities = knn.predict_proba(test_features)

display_predictions(
    5, 3,
    knn_probabilities,
    "K-Nearest Neighbors"
)

accuracy_knn = accuracy_score(
    test_labels.ravel(),
    knn_predictions
)

print(f"Accuracy for KNN: {accuracy_knn * 100:.2f}%")
# =========================
# NAIVE BAYES
# =========================

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
file_path = './keras_cifar10/nb_model.joblib'

if os.path.exists(file_path):
    print("Loading saved Naive Bayes model...")
    nb = joblib.load(file_path)
else:
    print("Training Naive Bayes...")
    nb.fit(
        train_features,
        train_labels.ravel()
    )
    joblib.dump(nb, file_path)

nb_predictions = nb.predict(test_features)
nb_probabilities = nb.predict_proba(test_features)

display_predictions(
    5, 3,
    nb_probabilities,
    "Gaussian Naive Bayes"
)

accuracy_nb = accuracy_score(
    test_labels.ravel(),
    nb_predictions
)

print(f"Accuracy for Naive Bayes: {accuracy_nb * 100:.2f}%")
# =========================
# DECISION TREE
# =========================

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    random_state=42
)

file_path = './keras_cifar10/dt_model.joblib'

if os.path.exists(file_path):
    print("Loading saved Decision Tree model...")
    dt = joblib.load(file_path)
else:
    print("Training Decision Tree...")
    dt.fit(
        train_features,
        train_labels.ravel()
    )
    joblib.dump(dt, file_path)

dt_predictions = dt.predict(test_features)
dt_probabilities = dt.predict_proba(test_features)

display_predictions(
    5, 3,
    dt_probabilities,
    "Decision Tree"
)
accuracy_dt = accuracy_score(
    test_labels.ravel(),
    dt_predictions
)

print(f"Accuracy for Decision Tree: {accuracy_dt * 100:.2f}%")
